name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report!
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      value: |
        I tried this:

        1. `coyote`

        I expected this to happen:

        Instead, this happened:
  - type: textarea
    id: coyote-log
    attributes:
      label: Coyote log
      description: Include the Coyote log file to help diagnose the issue. (`coyote --info` to see the log_path)
      value: |
        | OS      | Log file location                                     |
        | ------- | ----------------------------------------------------- |
        | Linux   | `~/.cache/coyote/coyote.log`                      |
        | Mac     | `~/Library/Logs/coyote/coyote.log`                |
        | Windows | `C:\Users\<User>\AppData\Local\coyote\coyote.log` |

        ```
        please provide a copy of your coyote log file here if possible; you may need to redact some of the lines
        ```

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: Linux / macOS / Windows
    validations:
      required: true
  - type: input
    id: terminal-emulator
    attributes:
      label: Terminal Emulator
      placeholder: wezterm 20220101-133340-7edc5b5a
    validations:
      required: true
  - type: input
    id: coyote-version
    attributes:
      label: Coyote Version
      description: >
        Coyote version (`coyote --version` if using a release, `git describe` if building
        from main).
        **Make sure that you are using the [latest coyote release](https://github.com/Dark-Alex-17/coyote/releases) or a newer main build**
      placeholder: "coyote 0.1.0"
    validations:
      required: true
